const OVERRIDES: Record<string, string> = {
  BTC: "/icons/crypto/btc.png",
  ETH: "/icons/crypto/eth.png",
  SOL: "/icons/crypto/sol.png",
  XRP: "/icons/crypto/xrp.png",
  ADA: "/icons/crypto/ada.png",
  DOGE: "/icons/crypto/doge.png",
  BNB: "/icons/crypto/bnb.png",
  UNI: "/icons/crypto/uni.png",
  LTC: "/icons/crypto/ltc.png",
  DOT: "/icons/crypto/dot.png",
  AVAX: "/icons/crypto/avax.png",
  POL: "/icons/crypto/pol.png",
  LINK: "/icons/crypto/link.png",
  USDT: "/icons/crypto/usdt.png",
  USDC: "/icons/crypto/usdc.png",
  SHIB: "/icons/crypto/shib.png",
  DAI: "/icons/crypto/dai.png",
  BCH: "/icons/crypto/bch.png",
  XLM: "/icons/crypto/xlm.png",
  NEAR: "/icons/crypto/near.png",
  VET: "/icons/crypto/vet.png",
  TRX: "/icons/crypto/trx.png",
  ATOM: "/icons/crypto/atom.png",
  SUI: "/icons/crypto/sui.png",
  ARB: "/icons/crypto/arb.png",
  FTM: "/icons/crypto/ftm.png",
  OP: "/icons/crypto/op.png",
  HYPE: "/icons/crypto/hype.png",
  PYUSD: "/icons/crypto/pyusd.png",
  TON: "/icons/crypto/ton.png",
  OKB: "/icons/crypto/okb.png",
  PI: "/icons/crypto/pi.png",
  LEO: "/icons/crypto/leo.png",
  XMR: "/icons/crypto/xmr.png",
  USDE: "/icons/crypto/usde.png",
  CC: "/icons/crypto/cc.png",
  WLFI: "/icons/crypto/wlfi.png",
  HBAR: "/icons/crypto/hbar.png",
  MNT: "/icons/crypto/mnt.png",
  PAXG: "/icons/crypto/paxg.png",
  PEPE: "/icons/crypto/pepe.png",
  FLOKI: "/icons/crypto/floki.png",
  AAVE: "/icons/crypto/aave.png",
  MKR: "/icons/crypto/mkr.png",
  CRO: "/icons/crypto/cro.png",
  TAO: "/icons/crypto/tao.png",
  USDG: "/icons/crypto/usdg.png",
  INJ: "/icons/crypto/inj.png",
  SKY: "/icons/crypto/sky.png",
  ICP: "/icons/crypto/icp.png",
};

export function getCryptoIconUrl(symbol: string): string | undefined {
  return OVERRIDES[symbol.toUpperCase()];
}