export const SYMBOL_META: Record<string, { name: string }> = {
  BTC: { name: "Bitcoin" },
  ETH: { name: "Ethereum" },
  SOL: { name: "Solana" },
  XRP: { name: "XRP" },
  ADA: { name: "Cardano" },
  BNB: { name: "BNB" },
  DOGE: { name: "Dogecoin" },
  POL: { name: "Polygon" },
  AVAX: { name: "Avalanche" },
  DOT: { name: "Polkadot" },
  LINK: { name: "Chainlink" },
  UNI: { name: "Uniswap" },
  LTC: { name: "Litecoin" },
  USDT:{ name:"Tether" },
  USDC:{ name: "USDC" },
  SHIB:{ name: "SHIBA Inu" },
  DAI:{ name: "DAI" },
  BCH:{ name: "Bitcoin Cash" },
  XLM:{ name: "Stellar" },
  NEAR:{ name: "NEAR" },
  VET:{ name: "VeChain" },
  TRX:{ name: "TRON" },
  ATOM:{ name: "Cosmos" },
  SUI: { name: "Sui" },
  ARB: { name: "Arbitrum" },
  FTM: { name: "Fantom" },
  OP: { name: "Optimism"},
  HYPE: { name: "Hyperliquid" },
  PYUSD: { name: "PayPal USD"},
  GRAM: { name: "Gram" },
  OKB: { name: "OKB" },
  PI: { name: "Pi Network" },
  LEO: { name: "LEO Token" },
  XMR: { name: "Monero" },
  USDE: { name: "Ethena USDe" },
  CC: { name: "Canton" },
  WLFI: { name: "World Liberty Financial" },
  HBAR: { name: "Hedera" },
  MNT: { name: "Mantle" },
  PAXG: { name: "Pax Gold" },
  PEPE: { name: "Pepe" },
  FLOKI: { name: "Floki" },
  AAVE: { name: "Aave" },
  MKR: { name: "Maker" },
  CRO: { name: "Cronos" },
  TAO: { name: "Bittensor" },
  USDG: { name: "Global Dollar" },
  INJ: { name: "Injective" },
  SKY: { name: "Sky" },
  ICP: { name: "Internet Computer" },
  APT: { name:  "Aptos" },
  ALGO: { name: "Algorand" },
  XTZ: { name: "Tezos" },
  EGLD: { name: "MultiversX" },
  FET: { name: "Artificial Superintelligence Alliance" },
  RENDER: { name: "Render" },
  ETHFI: { name: "Ether.fi" },
  GRT: { name: "The Graph" },
  JUP: { name: "Jupiter" },
  PYTH: { name: "Pyth Network" },
  QNT: { name: "Quant" },
  ZEC: { name: "Zcash" },
  USDS: { name: "USDS" },
  USD1: { name: "USD1" },
  XAUt: { name: "Tether Gold" },
  M: { name: "MemeCore" },
  DEXE: { name: "DeXe" },
  ASTER: { name: "Aster" },
  ONDO: { name: "Ondo" },
  RLUSD: { name: "Ripple USD" },
  USDD: { name: "USDD" },
  WLD: { name: "Worldcoin" },
  BGB: { name: "Bitget Token" },
  ETC: { name: "Ethereum Classic" },
  MORPHO: { name: "Morpho" },
  U: { name: "United Stables" },
  KCS: { name: "KuCoin" },
  BEAT: { name: "Audiera" },
  KAS: { name: "Kaspa" },
  STABLE: { name: "Stable" },
};
export function getSymbolName(symbol: string) {
  const key = symbol.toUpperCase();
  return SYMBOL_META[key]?.name;
}
