export type SymbolCategory =
  | "major" | "layer1" | "layer2" | "meme" | "defi" | "stablecoin"
  | "rwa" | "ai" | "privacy" | "infra" | "oracle" | "exchange-token"
  | "payments" | "gaming" | "store-of-value" | "smart-contracts";

export type SymbolMetaEntry = { name: string; icon?: string; categories?: SymbolCategory[]; };

export const SYMBOL_META: Record<string, SymbolMetaEntry> = {
  BTC: { name: "Bitcoin", icon: "/icons/crypto/btc.png", categories: ["major", "store-of-value"] },
  ETH: { name: "Ethereum", icon: "/icons/crypto/eth.png", categories: ["major", "layer1", "smart-contracts"] },
  SOL: { name: "Solana", icon: "/icons/crypto/sol.png", categories: ["major", "layer1"] },
  XRP: { name: "XRP", icon: "/icons/crypto/xrp.png", categories: ["major", "payments"] },
  ADA: { name: "Cardano", icon: "/icons/crypto/ada.png", categories: ["layer1"] },
  BNB: { name: "BNB", icon: "/icons/crypto/bnb.png", categories: ["major", "layer1"] },
  DOGE: { name: "Dogecoin", icon: "/icons/crypto/doge.png", categories: ["meme"] },
  POL: { name: "Polygon", icon: "/icons/crypto/pol.png", categories: ["layer2"] },
  AVAX: { name: "Avalanche", icon: "/icons/crypto/avax.png", categories: ["layer1"] },
  DOT: { name: "Polkadot", icon: "/icons/crypto/dot.png", categories: ["layer1"] },
  LINK: { name: "Chainlink", icon: "/icons/crypto/link.png", categories: ["oracle"] },
  UNI: { name: "Uniswap", icon: "/icons/crypto/uni.png", categories: ["defi"] },
  LTC: { name: "Litecoin", icon: "/icons/crypto/ltc.png", categories: ["payments"] },
  USDT: { name: "Tether", icon: "/icons/crypto/usdt.png", categories: ["stablecoin"] },
  USDC: { name: "USDC", icon: "/icons/crypto/usdc.png", categories: ["stablecoin"] },
  SHIB: { name: "SHIBA Inu", icon: "/icons/crypto/shib.png", categories: ["meme"] },
  DAI: { name: "DAI", icon: "/icons/crypto/dai.png", categories: ["stablecoin"] },
  BCH: { name: "Bitcoin Cash", icon: "/icons/crypto/bch.png", categories: ["layer1", "payments"] },
  XLM: { name: "Stellar", icon: "/icons/crypto/xlm.png", categories: ["layer1", "payments"] },
  NEAR: { name: "NEAR", icon: "/icons/crypto/near.png", categories: ["layer1"] },
  VET: { name: "VeChain", icon: "/icons/crypto/vet.png", categories: ["layer1"] },
  TRX: { name: "TRON", icon: "/icons/crypto/trx.png", categories: ["layer1"] },
  ATOM: { name: "Cosmos", icon: "/icons/crypto/atom.png", categories: ["layer1"] },
  SUI: { name: "Sui", icon: "/icons/crypto/sui.png", categories: ["layer1"] },
  ARB: { name: "Arbitrum", icon: "/icons/crypto/arb.png", categories: ["layer2"] },
  FTM: { name: "Fantom", icon: "/icons/crypto/ftm.png", categories: ["layer1"] },
  OP: { name: "Optimism", icon: "/icons/crypto/op.png", categories: ["layer2"] },
  HYPE: { name: "Hyperliquid", icon: "/icons/crypto/hype.png", categories: ["layer1", "defi"] },
  PYUSD: { name: "PayPal USD", icon: "/icons/crypto/pyusd.png", categories: ["stablecoin"] },
  GRAM: { name: "Gram", icon: "/icons/crypto/gram.png", categories: ["infra"] },
  OKB: { name: "OKB", icon: "/icons/crypto/okb.png", categories: ["exchange-token"] },
  PI: { name: "Pi Network", icon: "/icons/crypto/pi.png", categories: ["gaming"] },
  LEO: { name: "LEO Token", icon: "/icons/crypto/leo.png", categories: ["exchange-token"] },
  XMR: { name: "Monero", icon: "/icons/crypto/xmr.png", categories: ["privacy"] },
  USDE: { name: "Ethena USDe", icon: "/icons/crypto/usde.png", categories: ["stablecoin"] },
  CC: { name: "Canton", icon: "/icons/crypto/cc.png", categories: ["infra"] },
  WLFI: { name: "World Liberty Financial", icon: "/icons/crypto/wlfi.png", categories: ["rwa"] },
  HBAR: { name: "Hedera", icon: "/icons/crypto/hbar.png", categories: ["layer1"] },
  MNT: { name: "Mantle", icon: "/icons/crypto/mnt.png", categories: ["layer2"] },
  PAXG: { name: "Pax Gold", icon: "/icons/crypto/paxg.png", categories: ["rwa", "store-of-value"] },
  PEPE: { name: "Pepe", icon: "/icons/crypto/pepe.png", categories: ["meme"] },
  FLOKI: { name: "Floki", icon: "/icons/crypto/floki.png", categories: ["meme"] },
  AAVE: { name: "Aave", icon: "/icons/crypto/aave.png", categories: ["defi"] },
  MKR: { name: "Maker", icon: "/icons/crypto/mkr.png", categories: ["defi"] },
  CRO: { name: "Cronos", icon: "/icons/crypto/cro.png", categories: ["layer1", "exchange-token"] },
  TAO: { name: "Bittensor", icon: "/icons/crypto/tao.png", categories: ["ai"] },
  USDG: { name: "Global Dollar", icon: "/icons/crypto/usdg.png", categories: ["stablecoin"] },
  INJ: { name: "Injective", icon: "/icons/crypto/inj.png", categories: ["defi"] },
  SKY: { name: "Sky", icon: "/icons/crypto/sky.png", categories: ["defi"] },
  ICP: { name: "Internet Computer", icon: "/icons/crypto/icp.png", categories: ["layer1"] },
  APT: { name: "Aptos", icon: "/icons/crypto/apt.png", categories: ["layer1"] },
  ALGO: { name: "Algorand", icon: "/icons/crypto/algo.png", categories: ["layer1"] },
  XTZ: { name: "Tezos", icon: "/icons/crypto/xtz.png", categories: ["layer1"] },
  EGLD: { name: "MultiversX", icon: "/icons/crypto/egld.png", categories: ["layer1"] },
  FET: { name: "Artificial Superintelligence Alliance", icon: "/icons/crypto/fet.png", categories: ["ai"] },
  RENDER: { name: "Render", icon: "/icons/crypto/render.png", categories: ["ai"] },
  ETHFI: { name: "Ether.fi", icon: "/icons/crypto/ethfi.png", categories: ["defi"] },
  GRT: { name: "The Graph", icon: "/icons/crypto/grt.png", categories: ["infra"] },
  JUP: { name: "Jupiter", icon: "/icons/crypto/jup.png", categories: ["defi"] },
  PYTH: { name: "Pyth Network", icon: "/icons/crypto/pyth.png", categories: ["oracle"] },
  QNT: { name: "Quant", icon: "/icons/crypto/qnt.png", categories: ["infra"] },
  ZEC: { name: "Zcash", icon: "/icons/crypto/zec.png", categories: ["privacy"] },
  USDS: { name: "USDS", icon: "/icons/crypto/usds.png", categories: ["stablecoin"] },
  USD1: { name: "USD1", icon: "/icons/crypto/usd1.png", categories: ["stablecoin"] },
  XAUT: { name: "Tether Gold", icon: "/icons/crypto/xaut.png", categories: ["rwa", "store-of-value"] },
  M: { name: "MemeCore", icon: "/icons/crypto/m.png", categories: ["meme"] },
  DEXE: { name: "DeXe", icon: "/icons/crypto/dexe.png", categories: ["defi"] },
  ASTER: { name: "Aster", icon: "/icons/crypto/aster.png", categories: ["defi"] },
  ONDO: { name: "Ondo", icon: "/icons/crypto/ondo.png", categories: ["rwa"] },
  RLUSD: { name: "Ripple USD", icon: "/icons/crypto/rlusd.png", categories: ["stablecoin"] },
  USDD: { name: "USDD", icon: "/icons/crypto/usdd.png", categories: ["stablecoin"] },
  WLD: { name: "Worldcoin", icon: "/icons/crypto/wld.png", categories: ["ai"] },
  BGB: { name: "Bitget Token", icon: "/icons/crypto/bgb.png", categories: ["exchange-token"] },
  ETC: { name: "Ethereum Classic", icon: "/icons/crypto/etc.png", categories: ["layer1"] },
  MORPHO: { name: "Morpho", icon: "/icons/crypto/morpho.png", categories: ["defi"] },
  U: { name: "United Stables", icon: "/icons/crypto/u.png", categories: ["stablecoin"] },
  KCS: { name: "KuCoin", icon: "/icons/crypto/kcs.png", categories: ["exchange-token"] },
  BEAT: { name: "Audiera", icon: "/icons/crypto/beat.png", categories: ["gaming"] },
  KAS: { name: "Kaspa", icon: "/icons/crypto/kas.png", categories: ["layer1"] },
  STABLE: { name: "Stable", icon: "/icons/crypto/stable.png", categories: ["stablecoin"] },
  FIGR_HELOC: { name: "Figure Heloc", icon: "/icons/crypto/figr.png", categories: ["rwa"] },
  RAIN: { name: "Rain", icon: "/icons/crypto/rain.png", categories: ["stablecoin"] },
  WBT: { name: "WhiteBIT Coin", icon: "/icons/crypto/wbt.png", categories: ["exchange-token"] },
  AWETH: { name: "Aave v3 WETH", icon: "/icons/crypto/aweth.png", categories: ["defi"] },
  JST: { name: "JUST", icon: "/icons/crypto/jst.png", categories: ["defi"] },
  USDY: { name: "Ondo US Dollar Yield", icon: "/icons/crypto/usdy.png", categories: ["rwa", "stablecoin"] },
  LAB: { name: "LAB", icon: "/icons/crypto/lab.png", categories: ["defi"] },
  HTX: { name: "HTX DAO", icon: "/icons/crypto/htx.png", categories: ["exchange-token"] },
  USDF: { name: "Falcon USD", icon: "/icons/crypto/usdf.png", categories: ["stablecoin"] },
  BFUSD: { name: "BFUSD", icon: "/icons/crypto/bfusd.png", categories: ["stablecoin"] },
  EUTBL: { name: "Spiko EU T-Bills Money Market Fund", icon: "/icons/crypto/eutbl.png", categories: ["rwa"] },
  BDX: { name: "Beldex", icon: "/icons/crypto/bdx.png", categories: ["privacy"] },
  BCAP: { name: "Blockchain Capital", icon: "/icons/crypto/bcap.png", categories: ["rwa"] },
  USDGO: { name: "USDGO", icon: "/icons/crypto/usdgo.png", categories: ["stablecoin"] },
  NEXO: { name: "NEXO", icon: "/icons/crypto/nexo.png", categories: ["defi"] },
  ENA: { name: "Ethena", icon: "/icons/crypto/ena.png", categories: ["defi"] },
  ADI: { name: "ADI", icon: "/icons/crypto/adi.png", categories: ["stablecoin"] },
  GT: { name: "Gate", icon: "/icons/crypto/gt.png", categories: ["exchange-token"] },
  BUIDL: { name: "BlackRock USD Institutional Digital Liquidity Fund", icon: "/icons/crypto/buidl.png", categories: ["rwa"] },
  NIGHT: { name: "Midnight", icon: "/icons/crypto/night.png", categories: ["ai"] },
  USYC: { name: "Ondo US Dollar Yield Class C", icon: "/icons/crypto/usyc.png", categories: ["rwa", "stablecoin"] },
  A7A5: { name: "A7A5", icon: "/icons/crypto/A7A5.png", categories: ["stablecoin"] },
  TUSD: { name: "TrueUSD", icon: "/icons/crypto/tusd.png", categories: ["stablecoin"] },
  HASH: { name: "Provenance Blockchain", icon: "/icons/crypto/hash.png", categories: ["rwa", "infra"] },
  USX: { name: "USX", icon: "/icons/crypto/usx.png", categories: ["stablecoin"] },
  USD0: { name: "Usual USD", icon: "/icons/crypto/usd0.png", categories: ["stablecoin"] },
  FIL: { name: "Filecoin", icon: "/icons/crypto/fil.png", categories: ["infra"] },
  YLDS: { name: "YLDS", icon: "/icons/crypto/ylds.png", categories: ["rwa", "stablecoin"] },
  VVV: { name: "Venice Token", icon: "/icons/crypto/vvv.png", categories: ["ai"] },
  GHO: { name: "GHO", icon: "/icons/crypto/gho.png", categories: ["stablecoin"] },
  JAAA: { name: "Janus Henderson Anemoy Treasury Fund", icon: "/icons/crypto/jaaa.png", categories: ["rwa"] },
  PUMP: { name: "Pump.fun", icon: "/icons/crypto/pump.png", categories: ["defi"] },
  USTB: { name: "Invesco Short Duration US Government Securities Fund", icon: "/icons/crypto/ustb.png", categories: ["rwa"] },
  JTRSY: { name: "JTRSY", icon: "/icons/crypto/jtrsy.png", categories: ["rwa"] },
  EURSAFO: { name: "Spiko Amundi Overnight Swap Fund (EUR)", icon: "/icons/crypto/eursafo.png", categories: ["rwa"] },
  PENGU: { name: "Pudgy Penguins", icon: "/icons/crypto/pengu.png", categories: ["meme"] },
  ZAMA: { name: "Zama", icon: "/icons/crypto/zama.png", categories: ["ai"] },
  TRUMP: { name: "Official Trump", icon: "/icons/crypto/trump.png", categories: ["meme"] },
  '币安人生': { name: "币安人生 (BinanceLife)", icon: "/icons/crypto/币安人生.png", categories: ["meme"] },
  XDC: { name: "XDC Network", icon: "/icons/crypto/xdc.png", categories: ["layer1"] },
  FLR: { name: "Flare", icon: "/icons/crypto/flr.png", categories: ["layer1"] },
  EURC: { name: "Euro Coin", icon: "/icons/crypto/eurc.png", categories: ["stablecoin"] },
  PANCAKE: { name: "PancakeSwap", icon: "/icons/crypto/cake.png", categories: ["defi"] },
  AERO: { name: "Aerodrome Finance", icon: "/icons/crypto/aero.png", categories: ["defi"] },
  DASH: { name: "Dash", icon: "/icons/crypto/dash.png", categories: ["privacy"] },
  SEI: { name: "Sei", icon: "/icons/crypto/sei.png", categories: ["layer1"] },
  VIRTUAL: { name: "Virtuals Protocol", icon: "/icons/crypto/virtual.png", categories: ["ai"] },
  SUN: { name: "Sun Token", icon: "/icons/crypto/sun.png", categories: ["defi"] },
  CRV: { name: "Curve DAO", icon: "/icons/crypto/crv.png", categories: ["defi"] },
  FDUSD: { name: "First Digital USD", icon: "/icons/crypto/fdusd.png", categories: ["stablecoin"] },
  SPX: { name: "SPX6900", icon: "/icons/crypto/spx.png", categories: ["meme"] },
  TIA: { name: "Celestia", icon: "/icons/crypto/tia.png", categories: ["layer1"] },
  ZRO: { name: "LayerZero", icon: "/icons/crypto/zro.png", categories: ["infra"] },
  KAITO: { name: "Kaito", icon: "/icons/crypto/kaito.png", categories: ["ai"] },
  LDO: { name: "Lido DAO", icon: "/icons/crypto/ldo.png", categories: ["defi"] },
  GNO: { name: "Gnosis", icon: "/icons/crypto/gno.png", categories: ["defi"] },
  LUNC: { name: "Terra Luna Classic", icon: "/icons/crypto/lunc.png", categories: ["layer1"] },
  JTO: { name: "Jito", icon: "/icons/crypto/jto.png", categories: ["defi"] },
  NFT: { name: "AINFT", icon: "/icons/crypto/nft.png", categories: ["layer1"] },
  BONK: { name: "Bonk", icon: "/icons/crypto/bonk.png", categories: ["meme"] },
  BTT: { name: "BitTorrent", icon: "/icons/crypto/btt.png", categories: ["meme"] },
  BSV: { name: "Bitcoin SV", icon: "/icons/crypto/bsv.png", categories: ["layer1"] },
  MON: { name: "Monad", icon: "/icons/crypto/mon.png", categories: ["layer1"] },
  STX: { name: "Stacks", icon: "/icons/crypto/stx.png", categories: ["layer1"] },
  PENDLE: { name: "Pendle", icon: "/icons/crypto/pendle.png", categories: ["defi"] },
  CFX: { name: "Conflux", icon: "/icons/crypto/cfx.png", categories: ["layer1"] },
  IMX: { name: "Immutable", icon: "/icons/crypto/imx.png", categories: ["layer2", "gaming"] },
  JASMY: { name: "JasmyCoin", icon: "/icons/crypto/jasmy.png", categories: ["infra"] },
  DCR: { name: "Decred", icon: "/icons/crypto/dcr.png", categories: ["privacy"] },
  XPL: { name: "Plasma", icon: "/icons/crypto/xpl.png", categories: ["layer1"] },
};

export function getSymbolName(symbol: string): string | undefined {
  return SYMBOL_META[symbol.toUpperCase()]?.name;
}
export function getCryptoIconUrl(symbol: string): string | undefined {
  return SYMBOL_META[symbol.toUpperCase()]?.icon;
}
export function categoriesOf(symbol: string): SymbolCategory[] {
  return SYMBOL_META[symbol.toUpperCase()]?.categories ?? [];
}
export function hasCategory(symbol: string, cat: SymbolCategory): boolean {
  return categoriesOf(symbol).includes(cat);
}

/** Registro proactivo de símbolos vistos sin metadata (ej. nuevos del trending). */
const seenUnmapped = new Set<string>();
export function noteIfUnmapped(symbol: string): void {
  const k = symbol.toUpperCase();
  if (!SYMBOL_META[k] && !seenUnmapped.has(k)) {
    seenUnmapped.add(k);
    if (typeof console !== "undefined") console.warn(`[symbol_meta] sin metadata: ${k}`);
  }
}
export function getUnmappedSeen(): string[] { return [...seenUnmapped]; }
